-- MyÚčto.cz — Epic F2: seed definic výkazů dle vyhlášky 500/2002 Sb. (přílohy 1 a 2)
--
-- Jediná verze 'vyhl500-2002/2024' (valid_from 2000-01-01, valid_to NULL) pro
-- rozvahu i VZZ (druhové členění). Řádky tvoří strom přes parent_row_code;
-- prefix 'P.' v row_code odlišuje pasiva od aktiv (display_code = bez prefixu).
-- Mapa účtů: přesné 3místné syntetické kódy, target gross/correction,
-- balance_condition pro saldové účty (R8); odčitatelné položky (252, 429, 432)
-- vycházejí záporně přirozeně (debetní zůstatek v pasivech), sign zůstává 1.
--
-- Doplňky nad rámec tabulek specu (křížová kontrola s ChartOfAccountsTemplate, T7):
--   111 (Pořízení materiálu)            → C.I.1.  (Materiál)
--   491 (Účet individuálního podnikatele) → P.A.I.1. (Základní kapitál)
--   481 debetní zůstatek → C.II.1.4. Odložená daňová pohledávka (povinná položka přílohy 1)
--   666 (Výnosy z krátkodobého fin. majetku) → VI. Výnosové úroky a podobné výnosy (ne V. — ta je jen pro dlouhodobý FM)
--
-- Idempotence: INSERT IGNORE nad unikátními klíči (uq_sv_type_code,
-- uq_sr_version_code, uq_sam).

SET NAMES utf8mb4;

INSERT IGNORE INTO statement_versions (statement_type, version_code, valid_from, valid_to)
VALUES ('balance_sheet','vyhl500-2002/2024','2000-01-01',NULL),
       ('income_statement','vyhl500-2002/2024','2000-01-01',NULL);

SET @bs := (SELECT id FROM statement_versions WHERE statement_type='balance_sheet'   AND version_code='vyhl500-2002/2024');
SET @is := (SELECT id FROM statement_versions WHERE statement_type='income_statement' AND version_code='vyhl500-2002/2024');

-- ── Řádky ROZVAHY — AKTIVA ────────────────────────────────────────────────────

INSERT IGNORE INTO statement_rows (version_id, row_code, parent_row_code, section, label, level, position, row_type, calc_key) VALUES
(@bs, 'AKTIVA',      NULL,          'assets', 'AKTIVA CELKEM',                                        0,   1, 'subtotal', NULL),
(@bs, 'A.',          'AKTIVA',      'assets', 'Pohledávky za upsaný základní kapitál',                1,   2, 'detail',   NULL),
(@bs, 'B.',          'AKTIVA',      'assets', 'Stálá aktiva',                                         1,   3, 'subtotal', NULL),
(@bs, 'B.I.',        'B.',          'assets', 'Dlouhodobý nehmotný majetek',                          2,   4, 'subtotal', NULL),
(@bs, 'B.I.1.',      'B.I.',        'assets', 'Nehmotné výsledky vývoje',                             3,   5, 'detail',   NULL),
(@bs, 'B.I.2.',      'B.I.',        'assets', 'Ocenitelná práva',                                     3,   6, 'subtotal', NULL),
(@bs, 'B.I.2.1.',    'B.I.2.',      'assets', 'Software',                                             4,   7, 'detail',   NULL),
(@bs, 'B.I.2.2.',    'B.I.2.',      'assets', 'Ostatní ocenitelná práva',                             4,   8, 'detail',   NULL),
(@bs, 'B.I.3.',      'B.I.',        'assets', 'Goodwill',                                             3,   9, 'detail',   NULL),
(@bs, 'B.I.4.',      'B.I.',        'assets', 'Ostatní dlouhodobý nehmotný majetek',                  3,  10, 'detail',   NULL),
(@bs, 'B.I.5.',      'B.I.',        'assets', 'Poskytnuté zálohy na DNM a nedokončený DNM',           3,  11, 'subtotal', NULL),
(@bs, 'B.I.5.1.',    'B.I.5.',      'assets', 'Poskytnuté zálohy na dlouhodobý nehmotný majetek',     4,  12, 'detail',   NULL),
(@bs, 'B.I.5.2.',    'B.I.5.',      'assets', 'Nedokončený dlouhodobý nehmotný majetek',              4,  13, 'detail',   NULL),
(@bs, 'B.II.',       'B.',          'assets', 'Dlouhodobý hmotný majetek',                            2,  14, 'subtotal', NULL),
(@bs, 'B.II.1.',     'B.II.',       'assets', 'Pozemky a stavby',                                     3,  15, 'subtotal', NULL),
(@bs, 'B.II.1.1.',   'B.II.1.',     'assets', 'Pozemky',                                              4,  16, 'detail',   NULL),
(@bs, 'B.II.1.2.',   'B.II.1.',     'assets', 'Stavby',                                               4,  17, 'detail',   NULL),
(@bs, 'B.II.2.',     'B.II.',       'assets', 'Hmotné movité věci a jejich soubory',                  3,  18, 'detail',   NULL),
(@bs, 'B.II.3.',     'B.II.',       'assets', 'Oceňovací rozdíly k nabytému majetku',                 3,  19, 'detail',   NULL),
(@bs, 'B.II.4.',     'B.II.',       'assets', 'Ostatní dlouhodobý hmotný majetek',                    3,  20, 'subtotal', NULL),
(@bs, 'B.II.4.1.',   'B.II.4.',     'assets', 'Pěstitelské celky trvalých porostů',                   4,  21, 'detail',   NULL),
(@bs, 'B.II.4.2.',   'B.II.4.',     'assets', 'Dospělá zvířata a jejich skupiny',                     4,  22, 'detail',   NULL),
(@bs, 'B.II.4.3.',   'B.II.4.',     'assets', 'Jiný dlouhodobý hmotný majetek',                       4,  23, 'detail',   NULL),
(@bs, 'B.II.5.',     'B.II.',       'assets', 'Poskytnuté zálohy na DHM a nedokončený DHM',           3,  24, 'subtotal', NULL),
(@bs, 'B.II.5.1.',   'B.II.5.',     'assets', 'Poskytnuté zálohy na dlouhodobý hmotný majetek',       4,  25, 'detail',   NULL),
(@bs, 'B.II.5.2.',   'B.II.5.',     'assets', 'Nedokončený dlouhodobý hmotný majetek',                4,  26, 'detail',   NULL),
(@bs, 'B.III.',      'B.',          'assets', 'Dlouhodobý finanční majetek',                          2,  27, 'subtotal', NULL),
(@bs, 'B.III.1.',    'B.III.',      'assets', 'Podíly — ovládaná nebo ovládající osoba',              3,  28, 'detail',   NULL),
(@bs, 'B.III.2.',    'B.III.',      'assets', 'Zápůjčky a úvěry — ovládaná nebo ovládající osoba',    3,  29, 'detail',   NULL),
(@bs, 'B.III.3.',    'B.III.',      'assets', 'Podíly — podstatný vliv',                              3,  30, 'detail',   NULL),
(@bs, 'B.III.4.',    'B.III.',      'assets', 'Zápůjčky a úvěry — podstatný vliv',                    3,  31, 'detail',   NULL),
(@bs, 'B.III.5.',    'B.III.',      'assets', 'Ostatní dlouhodobé cenné papíry a podíly',             3,  32, 'detail',   NULL),
(@bs, 'B.III.6.',    'B.III.',      'assets', 'Zápůjčky a úvěry — ostatní',                           3,  33, 'detail',   NULL),
(@bs, 'B.III.7.',    'B.III.',      'assets', 'Ostatní dlouhodobý finanční majetek',                  3,  34, 'subtotal', NULL),
(@bs, 'B.III.7.1.',  'B.III.7.',    'assets', 'Jiný dlouhodobý finanční majetek',                     4,  35, 'detail',   NULL),
(@bs, 'B.III.7.2.',  'B.III.7.',    'assets', 'Poskytnuté zálohy na dlouhodobý finanční majetek',     4,  36, 'detail',   NULL),
(@bs, 'C.',          'AKTIVA',      'assets', 'Oběžná aktiva',                                        1,  37, 'subtotal', NULL),
(@bs, 'C.I.',        'C.',          'assets', 'Zásoby',                                               2,  38, 'subtotal', NULL),
(@bs, 'C.I.1.',      'C.I.',        'assets', 'Materiál',                                             3,  39, 'detail',   NULL),
(@bs, 'C.I.2.',      'C.I.',        'assets', 'Nedokončená výroba a polotovary',                      3,  40, 'detail',   NULL),
(@bs, 'C.I.3.',      'C.I.',        'assets', 'Výrobky a zboží',                                      3,  41, 'subtotal', NULL),
(@bs, 'C.I.3.1.',    'C.I.3.',      'assets', 'Výrobky',                                              4,  42, 'detail',   NULL),
(@bs, 'C.I.3.2.',    'C.I.3.',      'assets', 'Zboží',                                                4,  43, 'detail',   NULL),
(@bs, 'C.I.4.',      'C.I.',        'assets', 'Mladá a ostatní zvířata a jejich skupiny',             3,  44, 'detail',   NULL),
(@bs, 'C.I.5.',      'C.I.',        'assets', 'Poskytnuté zálohy na zásoby',                          3,  45, 'detail',   NULL),
(@bs, 'C.II.',       'C.',          'assets', 'Pohledávky',                                           2,  46, 'subtotal', NULL),
(@bs, 'C.II.1.',     'C.II.',       'assets', 'Dlouhodobé pohledávky',                                3,  47, 'subtotal', NULL),
(@bs, 'C.II.1.1.',   'C.II.1.',     'assets', 'Pohledávky z obchodních vztahů',                       4,  48, 'detail',   NULL),
(@bs, 'C.II.1.4.',   'C.II.1.',     'assets', 'Odložená daňová pohledávka',                           4,  49, 'detail',   NULL),
(@bs, 'C.II.1.5.',   'C.II.1.',     'assets', 'Pohledávky — ostatní',                                 4,  50, 'detail',   NULL),
(@bs, 'C.II.2.',     'C.II.',       'assets', 'Krátkodobé pohledávky',                                3,  51, 'subtotal', NULL),
(@bs, 'C.II.2.1.',   'C.II.2.',     'assets', 'Pohledávky z obchodních vztahů',                       4,  52, 'detail',   NULL),
(@bs, 'C.II.2.2.',   'C.II.2.',     'assets', 'Pohledávky — ovládaná nebo ovládající osoba',          4,  53, 'detail',   NULL),
(@bs, 'C.II.2.3.',   'C.II.2.',     'assets', 'Pohledávky — podstatný vliv',                          4,  54, 'detail',   NULL),
(@bs, 'C.II.2.4.',   'C.II.2.',     'assets', 'Pohledávky — ostatní',                                 4,  55, 'subtotal', NULL),
(@bs, 'C.II.2.4.1.', 'C.II.2.4.',   'assets', 'Pohledávky za společníky',                             4,  56, 'detail',   NULL),
(@bs, 'C.II.2.4.2.', 'C.II.2.4.',   'assets', 'Sociální zabezpečení a zdravotní pojištění',           4,  57, 'detail',   NULL),
(@bs, 'C.II.2.4.3.', 'C.II.2.4.',   'assets', 'Stát — daňové pohledávky',                             4,  58, 'detail',   NULL),
(@bs, 'C.II.2.4.4.', 'C.II.2.4.',   'assets', 'Krátkodobé poskytnuté zálohy',                         4,  59, 'detail',   NULL),
(@bs, 'C.II.2.4.5.', 'C.II.2.4.',   'assets', 'Dohadné účty aktivní',                                 4,  60, 'detail',   NULL),
(@bs, 'C.II.2.4.6.', 'C.II.2.4.',   'assets', 'Jiné pohledávky',                                      4,  61, 'detail',   NULL),
(@bs, 'C.III.',      'C.',          'assets', 'Krátkodobý finanční majetek',                          2,  62, 'subtotal', NULL),
(@bs, 'C.III.1.',    'C.III.',      'assets', 'Podíly — ovládaná nebo ovládající osoba',              3,  63, 'detail',   NULL),
(@bs, 'C.III.2.',    'C.III.',      'assets', 'Ostatní krátkodobý finanční majetek',                  3,  64, 'detail',   NULL),
(@bs, 'C.IV.',       'C.',          'assets', 'Peněžní prostředky',                                   2,  65, 'subtotal', NULL),
(@bs, 'C.IV.1.',     'C.IV.',       'assets', 'Peněžní prostředky v pokladně',                        3,  66, 'detail',   NULL),
(@bs, 'C.IV.2.',     'C.IV.',       'assets', 'Peněžní prostředky na účtech',                         3,  67, 'detail',   NULL),
(@bs, 'D.',          'AKTIVA',      'assets', 'Časové rozlišení aktiv',                               1,  68, 'subtotal', NULL),
(@bs, 'D.1.',        'D.',          'assets', 'Náklady příštích období',                              3,  69, 'detail',   NULL),
(@bs, 'D.2.',        'D.',          'assets', 'Komplexní náklady příštích období',                    3,  70, 'detail',   NULL),
(@bs, 'D.3.',        'D.',          'assets', 'Příjmy příštích období',                               3,  71, 'detail',   NULL);

-- ── Řádky ROZVAHY — PASIVA ────────────────────────────────────────────────────

INSERT IGNORE INTO statement_rows (version_id, row_code, parent_row_code, section, label, level, position, row_type, calc_key) VALUES
(@bs, 'PASIVA',      NULL,          'liabilities', 'PASIVA CELKEM',                                                0,  72, 'subtotal', NULL),
(@bs, 'P.A.',        'PASIVA',      'liabilities', 'Vlastní kapitál',                                              1,  73, 'subtotal', NULL),
(@bs, 'P.A.I.',      'P.A.',        'liabilities', 'Základní kapitál',                                             2,  74, 'subtotal', NULL),
(@bs, 'P.A.I.1.',    'P.A.I.',      'liabilities', 'Základní kapitál',                                             3,  75, 'detail',   NULL),
(@bs, 'P.A.I.2.',    'P.A.I.',      'liabilities', 'Vlastní podíly (−)',                                           3,  76, 'detail',   NULL),
(@bs, 'P.A.I.3.',    'P.A.I.',      'liabilities', 'Změny základního kapitálu',                                    3,  77, 'detail',   NULL),
(@bs, 'P.A.II.',     'P.A.',        'liabilities', 'Ážio a kapitálové fondy',                                      2,  78, 'subtotal', NULL),
(@bs, 'P.A.II.1.',   'P.A.II.',     'liabilities', 'Ážio',                                                         3,  79, 'detail',   NULL),
(@bs, 'P.A.II.2.',   'P.A.II.',     'liabilities', 'Kapitálové fondy',                                             3,  80, 'subtotal', NULL),
(@bs, 'P.A.II.2.1.', 'P.A.II.2.',   'liabilities', 'Ostatní kapitálové fondy',                                     4,  81, 'detail',   NULL),
(@bs, 'P.A.II.2.2.', 'P.A.II.2.',   'liabilities', 'Oceňovací rozdíly z přecenění majetku a závazků (±)',          4,  82, 'detail',   NULL),
(@bs, 'P.A.III.',    'P.A.',        'liabilities', 'Fondy ze zisku',                                               2,  83, 'subtotal', NULL),
(@bs, 'P.A.III.1.',  'P.A.III.',    'liabilities', 'Ostatní rezervní fondy',                                       3,  84, 'detail',   NULL),
(@bs, 'P.A.III.2.',  'P.A.III.',    'liabilities', 'Statutární a ostatní fondy',                                   3,  85, 'detail',   NULL),
(@bs, 'P.A.IV.',     'P.A.',        'liabilities', 'Výsledek hospodaření minulých let (±)',                        2,  86, 'subtotal', NULL),
(@bs, 'P.A.IV.1.',   'P.A.IV.',     'liabilities', 'Nerozdělený zisk nebo neuhrazená ztráta minulých let (±)',     3,  87, 'detail',   NULL),
(@bs, 'P.A.V.',      'P.A.',        'liabilities', 'Výsledek hospodaření běžného účetního období (±)',             2,  88, 'computed', 'profit_current'),
(@bs, 'P.A.VI.',     'P.A.',        'liabilities', 'Rozhodnuto o zálohové výplatě podílu na zisku (−)',            2,  89, 'detail',   NULL),
(@bs, 'P.B.',        'PASIVA',      'liabilities', 'Rezervy',                                                      1,  90, 'subtotal', NULL),
(@bs, 'P.B.2.',      'P.B.',        'liabilities', 'Rezerva na daň z příjmů',                                      3,  91, 'detail',   NULL),
(@bs, 'P.B.3.',      'P.B.',        'liabilities', 'Rezervy podle zvláštních právních předpisů',                   3,  92, 'detail',   NULL),
(@bs, 'P.B.4.',      'P.B.',        'liabilities', 'Ostatní rezervy',                                              3,  93, 'detail',   NULL),
(@bs, 'P.C.',        'PASIVA',      'liabilities', 'Závazky',                                                      1,  94, 'subtotal', NULL),
(@bs, 'P.C.I.',      'P.C.',        'liabilities', 'Dlouhodobé závazky',                                           2,  95, 'subtotal', NULL),
(@bs, 'P.C.I.1.',    'P.C.I.',      'liabilities', 'Vydané dluhopisy',                                             3,  96, 'detail',   NULL),
(@bs, 'P.C.I.2.',    'P.C.I.',      'liabilities', 'Závazky k úvěrovým institucím',                                3,  97, 'detail',   NULL),
(@bs, 'P.C.I.3.',    'P.C.I.',      'liabilities', 'Dlouhodobé přijaté zálohy',                                    3,  98, 'detail',   NULL),
(@bs, 'P.C.I.6.',    'P.C.I.',      'liabilities', 'Závazky — ovládaná nebo ovládající osoba',                     3,  99, 'detail',   NULL),
(@bs, 'P.C.I.8.',    'P.C.I.',      'liabilities', 'Odložený daňový závazek',                                      3, 100, 'detail',   NULL),
(@bs, 'P.C.I.9.',    'P.C.I.',      'liabilities', 'Závazky — ostatní',                                            3, 101, 'detail',   NULL),
(@bs, 'P.C.II.',     'P.C.',        'liabilities', 'Krátkodobé závazky',                                           2, 102, 'subtotal', NULL),
(@bs, 'P.C.II.1.',   'P.C.II.',     'liabilities', 'Vydané dluhopisy',                                             3, 103, 'detail',   NULL),
(@bs, 'P.C.II.2.',   'P.C.II.',     'liabilities', 'Závazky k úvěrovým institucím',                                3, 104, 'detail',   NULL),
(@bs, 'P.C.II.3.',   'P.C.II.',     'liabilities', 'Krátkodobé přijaté zálohy',                                    3, 105, 'detail',   NULL),
(@bs, 'P.C.II.4.',   'P.C.II.',     'liabilities', 'Závazky z obchodních vztahů',                                  3, 106, 'detail',   NULL),
(@bs, 'P.C.II.5.',   'P.C.II.',     'liabilities', 'Krátkodobé směnky k úhradě',                                   3, 107, 'detail',   NULL),
(@bs, 'P.C.II.6.',   'P.C.II.',     'liabilities', 'Závazky — ovládaná nebo ovládající osoba',                     3, 108, 'detail',   NULL),
(@bs, 'P.C.II.8.',   'P.C.II.',     'liabilities', 'Závazky ostatní',                                              3, 109, 'subtotal', NULL),
(@bs, 'P.C.II.8.1.', 'P.C.II.8.',   'liabilities', 'Závazky ke společníkům',                                       4, 110, 'detail',   NULL),
(@bs, 'P.C.II.8.2.', 'P.C.II.8.',   'liabilities', 'Krátkodobé finanční výpomoci',                                 4, 111, 'detail',   NULL),
(@bs, 'P.C.II.8.3.', 'P.C.II.8.',   'liabilities', 'Závazky k zaměstnancům',                                       4, 112, 'detail',   NULL),
(@bs, 'P.C.II.8.4.', 'P.C.II.8.',   'liabilities', 'Závazky ze sociálního zabezpečení a zdravotního pojištění',    4, 113, 'detail',   NULL),
(@bs, 'P.C.II.8.5.', 'P.C.II.8.',   'liabilities', 'Stát — daňové závazky a dotace',                               4, 114, 'detail',   NULL),
(@bs, 'P.C.II.8.6.', 'P.C.II.8.',   'liabilities', 'Dohadné účty pasivní',                                         4, 115, 'detail',   NULL),
(@bs, 'P.C.II.8.7.', 'P.C.II.8.',   'liabilities', 'Jiné závazky',                                                 4, 116, 'detail',   NULL),
(@bs, 'P.D.',        'PASIVA',      'liabilities', 'Časové rozlišení pasiv',                                       1, 117, 'subtotal', NULL),
(@bs, 'P.D.1.',      'P.D.',        'liabilities', 'Výdaje příštích období',                                       3, 118, 'detail',   NULL),
(@bs, 'P.D.2.',      'P.D.',        'liabilities', 'Výnosy příštích období',                                       3, 119, 'detail',   NULL);

-- ── Řádky VZZ (druhové členění) ───────────────────────────────────────────────

INSERT IGNORE INTO statement_rows (version_id, row_code, parent_row_code, section, label, level, position, row_type, calc_key) VALUES
(@is, 'I.',     NULL,     'profit_loss', 'Tržby z prodeje výrobků a služeb',                                 1,  1, 'detail',   NULL),
(@is, 'II.',    NULL,     'profit_loss', 'Tržby za prodej zboží',                                            1,  2, 'detail',   NULL),
(@is, 'A.',     NULL,     'profit_loss', 'Výkonová spotřeba',                                                1,  3, 'subtotal', NULL),
(@is, 'A.1.',   'A.',     'profit_loss', 'Náklady vynaložené na prodané zboží',                              2,  4, 'detail',   NULL),
(@is, 'A.2.',   'A.',     'profit_loss', 'Spotřeba materiálu a energie',                                     2,  5, 'detail',   NULL),
(@is, 'A.3.',   'A.',     'profit_loss', 'Služby',                                                           2,  6, 'detail',   NULL),
(@is, 'B.',     NULL,     'profit_loss', 'Změna stavu zásob vlastní činnosti (±)',                           1,  7, 'detail',   NULL),
(@is, 'C.',     NULL,     'profit_loss', 'Aktivace (−)',                                                     1,  8, 'detail',   NULL),
(@is, 'D.',     NULL,     'profit_loss', 'Osobní náklady',                                                   1,  9, 'subtotal', NULL),
(@is, 'D.1.',   'D.',     'profit_loss', 'Mzdové náklady',                                                   2, 10, 'detail',   NULL),
(@is, 'D.2.',   'D.',     'profit_loss', 'Náklady na soc. zabezpečení, zdrav. pojištění a ostatní náklady',  2, 11, 'subtotal', NULL),
(@is, 'D.2.1.', 'D.2.',   'profit_loss', 'Náklady na sociální zabezpečení a zdravotní pojištění',            3, 12, 'detail',   NULL),
(@is, 'D.2.2.', 'D.2.',   'profit_loss', 'Ostatní náklady',                                                  3, 13, 'detail',   NULL),
(@is, 'E.',     NULL,     'profit_loss', 'Úpravy hodnot v provozní oblasti',                                 1, 14, 'subtotal', NULL),
(@is, 'E.1.',   'E.',     'profit_loss', 'Úpravy hodnot DNM a DHM',                                          2, 15, 'subtotal', NULL),
(@is, 'E.1.1.', 'E.1.',   'profit_loss', '— trvalé',                                                         3, 16, 'detail',   NULL),
(@is, 'E.1.2.', 'E.1.',   'profit_loss', '— dočasné',                                                        3, 17, 'detail',   NULL),
(@is, 'E.2.',   'E.',     'profit_loss', 'Úpravy hodnot zásob',                                              2, 18, 'detail',   NULL),
(@is, 'E.3.',   'E.',     'profit_loss', 'Úpravy hodnot pohledávek',                                         2, 19, 'detail',   NULL),
(@is, 'III.',   NULL,     'profit_loss', 'Ostatní provozní výnosy',                                          1, 20, 'subtotal', NULL),
(@is, 'III.1.', 'III.',   'profit_loss', 'Tržby z prodaného dlouhodobého majetku',                           2, 21, 'detail',   NULL),
(@is, 'III.2.', 'III.',   'profit_loss', 'Tržby z prodaného materiálu',                                      2, 22, 'detail',   NULL),
(@is, 'III.3.', 'III.',   'profit_loss', 'Jiné provozní výnosy',                                             2, 23, 'detail',   NULL),
(@is, 'F.',     NULL,     'profit_loss', 'Ostatní provozní náklady',                                         1, 24, 'subtotal', NULL),
(@is, 'F.1.',   'F.',     'profit_loss', 'Zůstatková cena prodaného dlouhodobého majetku',                   2, 25, 'detail',   NULL),
(@is, 'F.2.',   'F.',     'profit_loss', 'Prodaný materiál',                                                 2, 26, 'detail',   NULL),
(@is, 'F.3.',   'F.',     'profit_loss', 'Daně a poplatky',                                                  2, 27, 'detail',   NULL),
(@is, 'F.4.',   'F.',     'profit_loss', 'Rezervy v provozní oblasti a komplexní náklady příštích období',   2, 28, 'detail',   NULL),
(@is, 'F.5.',   'F.',     'profit_loss', 'Jiné provozní náklady',                                            2, 29, 'detail',   NULL),
(@is, 'PVH',    NULL,     'profit_loss', 'Provozní výsledek hospodaření (±)',                                1, 30, 'computed', 'operating_profit'),
(@is, 'IV.',    NULL,     'profit_loss', 'Výnosy z dlouhodobého finančního majetku — podíly',                1, 31, 'detail',   NULL),
(@is, 'G.',     NULL,     'profit_loss', 'Náklady vynaložené na prodané podíly',                             1, 32, 'detail',   NULL),
(@is, 'V.',     NULL,     'profit_loss', 'Výnosy z ostatního dlouhodobého finančního majetku',               1, 33, 'detail',   NULL),
(@is, 'H.',     NULL,     'profit_loss', 'Náklady související s ostatním dlouhodobým finančním majetkem',    1, 34, 'detail',   NULL),
(@is, 'VI.',    NULL,     'profit_loss', 'Výnosové úroky a podobné výnosy',                                  1, 35, 'detail',   NULL),
(@is, 'I.n',    NULL,     'profit_loss', 'Úpravy hodnot a rezervy ve finanční oblasti',                      1, 36, 'detail',   NULL),
(@is, 'J.',     NULL,     'profit_loss', 'Nákladové úroky a podobné náklady',                                1, 37, 'detail',   NULL),
(@is, 'VII.',   NULL,     'profit_loss', 'Ostatní finanční výnosy',                                          1, 38, 'detail',   NULL),
(@is, 'K.',     NULL,     'profit_loss', 'Ostatní finanční náklady',                                         1, 39, 'detail',   NULL),
(@is, 'FVH',    NULL,     'profit_loss', 'Finanční výsledek hospodaření (±)',                                1, 40, 'computed', 'financial_profit'),
(@is, 'VHPZ',   NULL,     'profit_loss', 'Výsledek hospodaření před zdaněním (±)',                           1, 41, 'computed', 'profit_before_tax'),
(@is, 'L.',     NULL,     'profit_loss', 'Daň z příjmů',                                                     1, 42, 'subtotal', NULL),
(@is, 'L.1.',   'L.',     'profit_loss', 'Daň z příjmů splatná',                                             2, 43, 'detail',   NULL),
(@is, 'L.2.',   'L.',     'profit_loss', 'Daň z příjmů odložená (±)',                                        2, 44, 'detail',   NULL),
(@is, 'VHPO',   NULL,     'profit_loss', 'Výsledek hospodaření po zdanění (±)',                              1, 45, 'computed', 'profit_after_tax'),
(@is, 'M.',     NULL,     'profit_loss', 'Převod podílu na výsledku hospodaření společníkům (±)',            1, 46, 'detail',   NULL),
(@is, 'VH',     NULL,     'profit_loss', 'Výsledek hospodaření za účetní období (±)',                        1, 47, 'computed', 'profit_current'),
(@is, 'OBRAT',  NULL,     'profit_loss', 'Čistý obrat za účetní období',                                     1, 48, 'computed', 'net_turnover');

-- ── Mapa účtů ROZVAHY — AKTIVA ────────────────────────────────────────────────

INSERT IGNORE INTO statement_account_map (version_id, row_code, account_prefix, target, balance_condition, sign) VALUES
(@bs, 'A.',          '353', 'gross',      'any',    1),
(@bs, 'B.I.1.',      '012', 'gross',      'any',    1),
(@bs, 'B.I.2.1.',    '013', 'gross',      'any',    1),
(@bs, 'B.I.2.2.',    '014', 'gross',      'any',    1),
(@bs, 'B.I.3.',      '015', 'gross',      'any',    1),
(@bs, 'B.I.4.',      '019', 'gross',      'any',    1),
(@bs, 'B.I.5.1.',    '051', 'gross',      'any',    1),
(@bs, 'B.I.5.2.',    '041', 'gross',      'any',    1),
(@bs, 'B.I.',        '072', 'correction', 'any',    1),
(@bs, 'B.I.',        '073', 'correction', 'any',    1),
(@bs, 'B.I.',        '074', 'correction', 'any',    1),
(@bs, 'B.I.',        '075', 'correction', 'any',    1),
(@bs, 'B.I.',        '079', 'correction', 'any',    1),
(@bs, 'B.I.',        '091', 'correction', 'any',    1),
(@bs, 'B.II.1.1.',   '031', 'gross',      'any',    1),
(@bs, 'B.II.1.2.',   '021', 'gross',      'any',    1),
(@bs, 'B.II.2.',     '022', 'gross',      'any',    1),
(@bs, 'B.II.3.',     '097', 'gross',      'any',    1),
(@bs, 'B.II.4.1.',   '025', 'gross',      'any',    1),
(@bs, 'B.II.4.2.',   '026', 'gross',      'any',    1),
(@bs, 'B.II.4.3.',   '029', 'gross',      'any',    1),
(@bs, 'B.II.4.3.',   '032', 'gross',      'any',    1),
(@bs, 'B.II.5.1.',   '052', 'gross',      'any',    1),
(@bs, 'B.II.5.2.',   '042', 'gross',      'any',    1),
(@bs, 'B.II.',       '081', 'correction', 'any',    1),
(@bs, 'B.II.',       '082', 'correction', 'any',    1),
(@bs, 'B.II.',       '085', 'correction', 'any',    1),
(@bs, 'B.II.',       '086', 'correction', 'any',    1),
(@bs, 'B.II.',       '088', 'correction', 'any',    1),
(@bs, 'B.II.',       '089', 'correction', 'any',    1),
(@bs, 'B.II.',       '092', 'correction', 'any',    1),
(@bs, 'B.II.',       '098', 'correction', 'any',    1),
(@bs, 'B.II.5.1.',   '095', 'correction', 'any',    1),
(@bs, 'B.III.1.',    '061', 'gross',      'any',    1),
(@bs, 'B.III.2.',    '066', 'gross',      'any',    1),
(@bs, 'B.III.3.',    '062', 'gross',      'any',    1),
(@bs, 'B.III.4.',    '067', 'gross',      'any',    1),
(@bs, 'B.III.5.',    '063', 'gross',      'any',    1),
(@bs, 'B.III.5.',    '065', 'gross',      'any',    1),
(@bs, 'B.III.6.',    '068', 'gross',      'any',    1),
(@bs, 'B.III.7.1.',  '069', 'gross',      'any',    1),
(@bs, 'B.III.7.2.',  '043', 'gross',      'any',    1),
(@bs, 'B.III.7.2.',  '053', 'gross',      'any',    1),
(@bs, 'B.III.',      '096', 'correction', 'any',    1),
(@bs, 'C.I.1.',      '111', 'gross',      'any',    1),
(@bs, 'C.I.1.',      '112', 'gross',      'any',    1),
(@bs, 'C.I.1.',      '119', 'gross',      'any',    1),
(@bs, 'C.I.2.',      '121', 'gross',      'any',    1),
(@bs, 'C.I.2.',      '122', 'gross',      'any',    1),
(@bs, 'C.I.3.1.',    '123', 'gross',      'any',    1),
(@bs, 'C.I.3.2.',    '131', 'gross',      'any',    1),
(@bs, 'C.I.3.2.',    '132', 'gross',      'any',    1),
(@bs, 'C.I.3.2.',    '139', 'gross',      'any',    1),
(@bs, 'C.I.4.',      '124', 'gross',      'any',    1),
(@bs, 'C.I.5.',      '151', 'gross',      'any',    1),
(@bs, 'C.I.5.',      '152', 'gross',      'any',    1),
(@bs, 'C.I.5.',      '153', 'gross',      'any',    1),
(@bs, 'C.I.',        '191', 'correction', 'any',    1),
(@bs, 'C.I.',        '192', 'correction', 'any',    1),
(@bs, 'C.I.',        '193', 'correction', 'any',    1),
(@bs, 'C.I.',        '194', 'correction', 'any',    1),
(@bs, 'C.I.',        '195', 'correction', 'any',    1),
(@bs, 'C.I.',        '196', 'correction', 'any',    1),
(@bs, 'C.II.2.1.',   '311', 'gross',      'any',    1),
(@bs, 'C.II.2.1.',   '312', 'gross',      'any',    1),
(@bs, 'C.II.2.1.',   '313', 'gross',      'any',    1),
(@bs, 'C.II.2.1.',   '315', 'gross',      'any',    1),
(@bs, 'C.II.2.2.',   '351', 'gross',      'any',    1),
(@bs, 'C.II.2.3.',   '352', 'gross',      'any',    1),
(@bs, 'C.II.2.4.1.', '355', 'gross',      'any',    1),
(@bs, 'C.II.2.4.2.', '336', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '341', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '342', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '343', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '344', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '345', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.3.', '346', 'gross',      'debit',  1),
(@bs, 'C.II.2.4.4.', '314', 'gross',      'any',    1),
(@bs, 'C.II.2.4.5.', '388', 'gross',      'any',    1),
(@bs, 'C.II.2.4.6.', '335', 'gross',      'any',    1),
(@bs, 'C.II.2.4.6.', '378', 'gross',      'any',    1),
(@bs, 'C.II.2.4.6.', '395', 'gross',      'debit',  1),
(@bs, 'C.II.1.4.',   '481', 'gross',      'debit',  1),
(@bs, 'C.II.',       '391', 'correction', 'any',    1),
(@bs, 'C.III.1.',    '254', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '251', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '253', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '255', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '256', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '257', 'gross',      'any',    1),
(@bs, 'C.III.2.',    '259', 'gross',      'any',    1),
(@bs, 'C.IV.1.',     '211', 'gross',      'any',    1),
(@bs, 'C.IV.1.',     '213', 'gross',      'any',    1),
(@bs, 'C.IV.1.',     '261', 'gross',      'debit',  1),
(@bs, 'C.IV.2.',     '221', 'gross',      'debit',  1),
(@bs, 'D.1.',        '381', 'gross',      'any',    1),
(@bs, 'D.2.',        '382', 'gross',      'any',    1),
(@bs, 'D.3.',        '385', 'gross',      'any',    1);

-- ── Mapa účtů ROZVAHY — PASIVA ────────────────────────────────────────────────

INSERT IGNORE INTO statement_account_map (version_id, row_code, account_prefix, target, balance_condition, sign) VALUES
(@bs, 'P.A.I.1.',    '411', 'gross', 'any',    1),
(@bs, 'P.A.I.1.',    '491', 'gross', 'any',    1),
(@bs, 'P.A.I.2.',    '252', 'gross', 'any',    1),
(@bs, 'P.A.I.3.',    '419', 'gross', 'any',    1),
(@bs, 'P.A.II.1.',   '412', 'gross', 'any',    1),
(@bs, 'P.A.II.2.1.', '413', 'gross', 'any',    1),
(@bs, 'P.A.II.2.2.', '414', 'gross', 'any',    1),
(@bs, 'P.A.III.1.',  '421', 'gross', 'any',    1),
(@bs, 'P.A.III.2.',  '423', 'gross', 'any',    1),
(@bs, 'P.A.III.2.',  '427', 'gross', 'any',    1),
(@bs, 'P.A.IV.1.',   '428', 'gross', 'any',    1),
(@bs, 'P.A.IV.1.',   '429', 'gross', 'any',    1),
(@bs, 'P.A.V.',      '431', 'gross', 'any',    1),
(@bs, 'P.A.VI.',     '432', 'gross', 'any',    1),
(@bs, 'P.B.2.',      '453', 'gross', 'any',    1),
(@bs, 'P.B.3.',      '451', 'gross', 'any',    1),
(@bs, 'P.B.4.',      '459', 'gross', 'any',    1),
(@bs, 'P.C.I.1.',    '473', 'gross', 'any',    1),
(@bs, 'P.C.I.2.',    '461', 'gross', 'any',    1),
(@bs, 'P.C.I.3.',    '475', 'gross', 'any',    1),
(@bs, 'P.C.I.6.',    '471', 'gross', 'any',    1),
(@bs, 'P.C.I.6.',    '472', 'gross', 'any',    1),
(@bs, 'P.C.I.8.',    '481', 'gross', 'credit', 1),
(@bs, 'P.C.I.9.',    '474', 'gross', 'any',    1),
(@bs, 'P.C.I.9.',    '478', 'gross', 'any',    1),
(@bs, 'P.C.I.9.',    '479', 'gross', 'any',    1),
(@bs, 'P.C.II.1.',   '241', 'gross', 'any',    1),
(@bs, 'P.C.II.2.',   '231', 'gross', 'any',    1),
(@bs, 'P.C.II.2.',   '232', 'gross', 'any',    1),
(@bs, 'P.C.II.2.',   '221', 'gross', 'credit', 1),
(@bs, 'P.C.II.3.',   '324', 'gross', 'any',    1),
(@bs, 'P.C.II.4.',   '321', 'gross', 'any',    1),
(@bs, 'P.C.II.4.',   '325', 'gross', 'any',    1),
(@bs, 'P.C.II.5.',   '322', 'gross', 'any',    1),
(@bs, 'P.C.II.6.',   '361', 'gross', 'any',    1),
(@bs, 'P.C.II.6.',   '362', 'gross', 'any',    1),
(@bs, 'P.C.II.8.1.', '364', 'gross', 'any',    1),
(@bs, 'P.C.II.8.1.', '365', 'gross', 'any',    1),
(@bs, 'P.C.II.8.1.', '366', 'gross', 'any',    1),
(@bs, 'P.C.II.8.1.', '367', 'gross', 'any',    1),
(@bs, 'P.C.II.8.2.', '249', 'gross', 'any',    1),
(@bs, 'P.C.II.8.3.', '331', 'gross', 'any',    1),
(@bs, 'P.C.II.8.3.', '333', 'gross', 'any',    1),
(@bs, 'P.C.II.8.4.', '336', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '341', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '342', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '343', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '344', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '345', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.5.', '346', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.6.', '389', 'gross', 'any',    1),
(@bs, 'P.C.II.8.7.', '372', 'gross', 'any',    1),
(@bs, 'P.C.II.8.7.', '373', 'gross', 'any',    1),
(@bs, 'P.C.II.8.7.', '379', 'gross', 'any',    1),
(@bs, 'P.C.II.8.7.', '395', 'gross', 'credit', 1),
(@bs, 'P.C.II.8.7.', '261', 'gross', 'credit', 1),
(@bs, 'P.D.1.',      '383', 'gross', 'any',    1),
(@bs, 'P.D.2.',      '384', 'gross', 'any',    1);

-- ── Mapa účtů VZZ ─────────────────────────────────────────────────────────────

INSERT IGNORE INTO statement_account_map (version_id, row_code, account_prefix, target, balance_condition, sign) VALUES
(@is, 'I.',     '601', 'gross', 'any', 1),
(@is, 'I.',     '602', 'gross', 'any', 1),
(@is, 'II.',    '604', 'gross', 'any', 1),
(@is, 'A.1.',   '504', 'gross', 'any', 1),
(@is, 'A.2.',   '501', 'gross', 'any', 1),
(@is, 'A.2.',   '502', 'gross', 'any', 1),
(@is, 'A.2.',   '503', 'gross', 'any', 1),
(@is, 'A.3.',   '511', 'gross', 'any', 1),
(@is, 'A.3.',   '512', 'gross', 'any', 1),
(@is, 'A.3.',   '513', 'gross', 'any', 1),
(@is, 'A.3.',   '518', 'gross', 'any', 1),
(@is, 'B.',     '581', 'gross', 'any', 1),
(@is, 'B.',     '582', 'gross', 'any', 1),
(@is, 'B.',     '583', 'gross', 'any', 1),
(@is, 'B.',     '584', 'gross', 'any', 1),
(@is, 'C.',     '585', 'gross', 'any', 1),
(@is, 'C.',     '586', 'gross', 'any', 1),
(@is, 'C.',     '587', 'gross', 'any', 1),
(@is, 'C.',     '588', 'gross', 'any', 1),
(@is, 'D.1.',   '521', 'gross', 'any', 1),
(@is, 'D.1.',   '522', 'gross', 'any', 1),
(@is, 'D.1.',   '523', 'gross', 'any', 1),
(@is, 'D.2.1.', '524', 'gross', 'any', 1),
(@is, 'D.2.1.', '525', 'gross', 'any', 1),
(@is, 'D.2.1.', '526', 'gross', 'any', 1),
(@is, 'D.2.2.', '527', 'gross', 'any', 1),
(@is, 'D.2.2.', '528', 'gross', 'any', 1),
(@is, 'E.1.1.', '551', 'gross', 'any', 1),
(@is, 'E.1.1.', '557', 'gross', 'any', 1),
(@is, 'E.1.2.', '559', 'gross', 'any', 1),
(@is, 'E.3.',   '558', 'gross', 'any', 1),
(@is, 'III.1.', '641', 'gross', 'any', 1),
(@is, 'III.2.', '642', 'gross', 'any', 1),
(@is, 'III.3.', '643', 'gross', 'any', 1),
(@is, 'III.3.', '644', 'gross', 'any', 1),
(@is, 'III.3.', '646', 'gross', 'any', 1),
(@is, 'III.3.', '647', 'gross', 'any', 1),
(@is, 'III.3.', '648', 'gross', 'any', 1),
(@is, 'F.1.',   '541', 'gross', 'any', 1),
(@is, 'F.2.',   '542', 'gross', 'any', 1),
(@is, 'F.3.',   '531', 'gross', 'any', 1),
(@is, 'F.3.',   '532', 'gross', 'any', 1),
(@is, 'F.3.',   '538', 'gross', 'any', 1),
(@is, 'F.4.',   '552', 'gross', 'any', 1),
(@is, 'F.4.',   '554', 'gross', 'any', 1),
(@is, 'F.4.',   '555', 'gross', 'any', 1),
(@is, 'F.5.',   '543', 'gross', 'any', 1),
(@is, 'F.5.',   '544', 'gross', 'any', 1),
(@is, 'F.5.',   '545', 'gross', 'any', 1),
(@is, 'F.5.',   '546', 'gross', 'any', 1),
(@is, 'F.5.',   '547', 'gross', 'any', 1),
(@is, 'F.5.',   '548', 'gross', 'any', 1),
(@is, 'F.5.',   '549', 'gross', 'any', 1),
(@is, 'IV.',    '665', 'gross', 'any', 1),
(@is, 'G.',     '561', 'gross', 'any', 1),
(@is, 'VI.',    '666', 'gross', 'any', 1),
(@is, 'H.',     '566', 'gross', 'any', 1),
(@is, 'VI.',    '662', 'gross', 'any', 1),
(@is, 'I.n',    '574', 'gross', 'any', 1),
(@is, 'I.n',    '579', 'gross', 'any', 1),
(@is, 'J.',     '562', 'gross', 'any', 1),
(@is, 'VII.',   '661', 'gross', 'any', 1),
(@is, 'VII.',   '663', 'gross', 'any', 1),
(@is, 'VII.',   '664', 'gross', 'any', 1),
(@is, 'VII.',   '668', 'gross', 'any', 1),
(@is, 'K.',     '563', 'gross', 'any', 1),
(@is, 'K.',     '564', 'gross', 'any', 1),
(@is, 'K.',     '567', 'gross', 'any', 1),
(@is, 'K.',     '568', 'gross', 'any', 1),
(@is, 'K.',     '569', 'gross', 'any', 1),
(@is, 'L.1.',   '591', 'gross', 'any', 1),
(@is, 'L.1.',   '595', 'gross', 'any', 1),
(@is, 'L.1.',   '599', 'gross', 'any', 1),
(@is, 'L.2.',   '592', 'gross', 'any', 1),
(@is, 'M.',     '596', 'gross', 'any', 1);
