UPDATE payroll_component_definitions
SET code = CASE code
    WHEN 'BASE_MONTHLY' THEN 'MZDA_MESICNI'
    WHEN 'BASE_HOURLY' THEN 'MZDA_HODINOVA'
    WHEN 'TASK_WAGE' THEN 'MZDA_UKOLOVA'
    WHEN 'BONUS' THEN 'ODMENA'
    WHEN 'PREMIUM' THEN 'PREMIE_PRIPLATKY'
    WHEN 'COMMISSION' THEN 'PROVIZE'
    WHEN 'WAGE_COMPENSATION' THEN 'NAHRADA_MZDY'
    WHEN 'SEVERANCE' THEN 'ODSTUPNE'
    WHEN 'COMPETITIVE_CLAUSE' THEN 'NAHRADA_KONKURENCNI_DOLOZKA'
    WHEN 'BACKPAY' THEN 'DOPLATEK_MZDY'
    WHEN 'NON_CASH' THEN 'NEPENEZNI_PRIJEM'
    WHEN 'BENEFIT_MEAL' THEN 'PRISPEVEK_STRAVOVANI'
    WHEN 'BENEFIT_VEHICLE' THEN 'SOUKROME_VOZIDLO'
    WHEN 'BENEFIT_PENSION' THEN 'PRISPEVEK_PENZE_ZIVOTNI'
    WHEN 'BENEFIT_CARE' THEN 'PRISPEVEK_DLOUHODOBA_PECE'
    WHEN 'BENEFIT_EDUCATION' THEN 'VZDELAVANI'
    WHEN 'BENEFIT_RECREATION' THEN 'REKREACE_VOLNY_CAS'
    WHEN 'BENEFIT_HEALTH' THEN 'ZDRAVOTNI_BENEFIT'
    WHEN 'RISKY_SAVINGS' THEN 'PRISPEVEK_RIZIKOVE_SPORENI'
    WHEN 'TRAVEL_REIMBURSEMENT' THEN 'CESTOVNI_NAHRADA'
    ELSE code
END
WHERE code IN (
    'BASE_MONTHLY',
    'BASE_HOURLY',
    'TASK_WAGE',
    'BONUS',
    'PREMIUM',
    'COMMISSION',
    'WAGE_COMPENSATION',
    'SEVERANCE',
    'COMPETITIVE_CLAUSE',
    'BACKPAY',
    'NON_CASH',
    'BENEFIT_MEAL',
    'BENEFIT_VEHICLE',
    'BENEFIT_PENSION',
    'BENEFIT_CARE',
    'BENEFIT_EDUCATION',
    'BENEFIT_RECREATION',
    'BENEFIT_HEALTH',
    'RISKY_SAVINGS',
    'TRAVEL_REIMBURSEMENT'
);
