-- Úplný číselník zemí podle ISO 3166-1 (249 států a území).
--
-- Do 1828 měl číselník jen EU a několik okolních států, takže převod adresáře z cizího
-- systému hlásil u partnerů z Ruska, Číny, Tchaj-wanu, Srbska a dalších „stát v číselníku
-- zemí není" a partner dostal zemi firmy.
--
-- Názvy (česky i anglicky) a kódy alpha-3 jsou vygenerované z ICU (PHP intl, ICU 77)
-- a zapsané staticky, ať migrace nezávisí na rozšíření intl.
--
-- Instalace mohou mít v číselníku země přidané ručně, s vlastními názvy i bez alpha-3.
-- Proto:
--   * nová země se vloží jen tehdy, když v tabulce není řádek se stejným iso2 ANI iso3
--     (unikátní klíč je jen na iso2, na iso3 se nezakládá, na existujících datech by
--     mohl narazit na duplicitu);
--   * existující řádek se nepřepisuje: id, názvy, iso3 ani is_eu zůstávají, doplní se
--     jen prázdné iso3 a prázdné názvy (iso3 jen tehdy, když ho nemá jiný řádek);
--   * nové země mají is_eu = 0, členské státy EU číselník obsahuje od 0001.
-- Idempotentní: opakovaný běh nic nevloží ani nezmění.

DROP TEMPORARY TABLE IF EXISTS tmp_1828_countries;
CREATE TEMPORARY TABLE tmp_1828_countries (
  iso2      CHAR(2) NOT NULL PRIMARY KEY,
  iso3      CHAR(3) NOT NULL,
  name_cs   VARCHAR(120) NOT NULL,
  name_en   VARCHAR(120) NOT NULL,
  iso3_free TINYINT(1) NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_1828_countries (iso2, iso3, name_cs, name_en, iso3_free) VALUES
('AD','AND','Andorra','Andorra',0),
('AE','ARE','Spojené arabské emiráty','United Arab Emirates',0),
('AF','AFG','Afghánistán','Afghanistan',0),
('AG','ATG','Antigua a Barbuda','Antigua & Barbuda',0),
('AI','AIA','Anguilla','Anguilla',0),
('AL','ALB','Albánie','Albania',0),
('AM','ARM','Arménie','Armenia',0),
('AO','AGO','Angola','Angola',0),
('AQ','ATA','Antarktida','Antarctica',0),
('AR','ARG','Argentina','Argentina',0),
('AS','ASM','Americká Samoa','American Samoa',0),
('AT','AUT','Rakousko','Austria',0),
('AU','AUS','Austrálie','Australia',0),
('AW','ABW','Aruba','Aruba',0),
('AX','ALA','Ålandy','Åland Islands',0),
('AZ','AZE','Ázerbájdžán','Azerbaijan',0),
('BA','BIH','Bosna a Hercegovina','Bosnia & Herzegovina',0),
('BB','BRB','Barbados','Barbados',0),
('BD','BGD','Bangladéš','Bangladesh',0),
('BE','BEL','Belgie','Belgium',0),
('BF','BFA','Burkina Faso','Burkina Faso',0),
('BG','BGR','Bulharsko','Bulgaria',0),
('BH','BHR','Bahrajn','Bahrain',0),
('BI','BDI','Burundi','Burundi',0),
('BJ','BEN','Benin','Benin',0),
('BL','BLM','Svatý Bartoloměj','St. Barthélemy',0),
('BM','BMU','Bermudy','Bermuda',0),
('BN','BRN','Brunej','Brunei',0),
('BO','BOL','Bolívie','Bolivia',0),
('BQ','BES','Karibské Nizozemsko','Caribbean Netherlands',0),
('BR','BRA','Brazílie','Brazil',0),
('BS','BHS','Bahamy','Bahamas',0),
('BT','BTN','Bhútán','Bhutan',0),
('BV','BVT','Bouvetův ostrov','Bouvet Island',0),
('BW','BWA','Botswana','Botswana',0),
('BY','BLR','Bělorusko','Belarus',0),
('BZ','BLZ','Belize','Belize',0),
('CA','CAN','Kanada','Canada',0),
('CC','CCK','Kokosové ostrovy','Cocos (Keeling) Islands',0),
('CD','COD','Kongo (DRK)','Congo (DRC)',0),
('CF','CAF','Středoafrická republika','Central African Republic',0),
('CG','COG','Kongo (republika)','Congo (Republic)',0),
('CH','CHE','Švýcarsko','Switzerland',0),
('CI','CIV','Pobřeží slonoviny','Côte d’Ivoire',0),
('CK','COK','Cookovy ostrovy','Cook Islands',0),
('CL','CHL','Chile','Chile',0),
('CM','CMR','Kamerun','Cameroon',0),
('CN','CHN','Čína','China',0),
('CO','COL','Kolumbie','Colombia',0),
('CR','CRI','Kostarika','Costa Rica',0),
('CU','CUB','Kuba','Cuba',0),
('CV','CPV','Kapverdy','Cape Verde',0),
('CW','CUW','Curaçao','Curaçao',0),
('CX','CXR','Vánoční ostrov','Christmas Island',0),
('CY','CYP','Kypr','Cyprus',0),
('CZ','CZE','Česko','Czechia',0),
('DE','DEU','Německo','Germany',0),
('DJ','DJI','Džibutsko','Djibouti',0),
('DK','DNK','Dánsko','Denmark',0),
('DM','DMA','Dominika','Dominica',0),
('DO','DOM','Dominikánská republika','Dominican Republic',0),
('DZ','DZA','Alžírsko','Algeria',0),
('EC','ECU','Ekvádor','Ecuador',0),
('EE','EST','Estonsko','Estonia',0),
('EG','EGY','Egypt','Egypt',0),
('EH','ESH','Západní Sahara','Western Sahara',0),
('ER','ERI','Eritrea','Eritrea',0),
('ES','ESP','Španělsko','Spain',0),
('ET','ETH','Etiopie','Ethiopia',0),
('FI','FIN','Finsko','Finland',0),
('FJ','FJI','Fidži','Fiji',0),
('FK','FLK','Falklandské ostrovy','Falkland Islands',0),
('FM','FSM','Mikronésie','Micronesia',0),
('FO','FRO','Faerské ostrovy','Faroe Islands',0),
('FR','FRA','Francie','France',0),
('GA','GAB','Gabon','Gabon',0),
('GB','GBR','Spojené království','United Kingdom',0),
('GD','GRD','Grenada','Grenada',0),
('GE','GEO','Gruzie','Georgia',0),
('GF','GUF','Francouzská Guyana','French Guiana',0),
('GG','GGY','Guernsey','Guernsey',0),
('GH','GHA','Ghana','Ghana',0),
('GI','GIB','Gibraltar','Gibraltar',0),
('GL','GRL','Grónsko','Greenland',0),
('GM','GMB','Gambie','Gambia',0),
('GN','GIN','Guinea','Guinea',0),
('GP','GLP','Guadeloupe','Guadeloupe',0),
('GQ','GNQ','Rovníková Guinea','Equatorial Guinea',0),
('GR','GRC','Řecko','Greece',0),
('GS','SGS','Jižní Georgie a Jižní Sandwichovy ostrovy','South Georgia & South Sandwich Islands',0),
('GT','GTM','Guatemala','Guatemala',0),
('GU','GUM','Guam','Guam',0),
('GW','GNB','Guinea-Bissau','Guinea-Bissau',0),
('GY','GUY','Guyana','Guyana',0),
('HK','HKG','Hongkong','Hong Kong',0),
('HM','HMD','Heardův ostrov a McDonaldovy ostrovy','Heard & McDonald Islands',0),
('HN','HND','Honduras','Honduras',0),
('HR','HRV','Chorvatsko','Croatia',0),
('HT','HTI','Haiti','Haiti',0),
('HU','HUN','Maďarsko','Hungary',0),
('ID','IDN','Indonésie','Indonesia',0),
('IE','IRL','Irsko','Ireland',0),
('IL','ISR','Izrael','Israel',0),
('IM','IMN','Ostrov Man','Isle of Man',0),
('IN','IND','Indie','India',0),
('IO','IOT','Britské indickooceánské území','British Indian Ocean Territory',0),
('IQ','IRQ','Irák','Iraq',0),
('IR','IRN','Írán','Iran',0),
('IS','ISL','Island','Iceland',0),
('IT','ITA','Itálie','Italy',0),
('JE','JEY','Jersey','Jersey',0),
('JM','JAM','Jamajka','Jamaica',0),
('JO','JOR','Jordánsko','Jordan',0),
('JP','JPN','Japonsko','Japan',0),
('KE','KEN','Keňa','Kenya',0),
('KG','KGZ','Kyrgyzstán','Kyrgyzstan',0),
('KH','KHM','Kambodža','Cambodia',0),
('KI','KIR','Kiribati','Kiribati',0),
('KM','COM','Komory','Comoros',0),
('KN','KNA','Svatý Kryštof a Nevis','St. Kitts & Nevis',0),
('KP','PRK','Severní Korea','North Korea',0),
('KR','KOR','Jižní Korea','South Korea',0),
('KW','KWT','Kuvajt','Kuwait',0),
('KY','CYM','Kajmanské ostrovy','Cayman Islands',0),
('KZ','KAZ','Kazachstán','Kazakhstan',0),
('LA','LAO','Laos','Laos',0),
('LB','LBN','Libanon','Lebanon',0),
('LC','LCA','Svatá Lucie','St. Lucia',0),
('LI','LIE','Lichtenštejnsko','Liechtenstein',0),
('LK','LKA','Srí Lanka','Sri Lanka',0),
('LR','LBR','Libérie','Liberia',0),
('LS','LSO','Lesotho','Lesotho',0),
('LT','LTU','Litva','Lithuania',0),
('LU','LUX','Lucembursko','Luxembourg',0),
('LV','LVA','Lotyšsko','Latvia',0),
('LY','LBY','Libye','Libya',0),
('MA','MAR','Maroko','Morocco',0),
('MC','MCO','Monako','Monaco',0),
('MD','MDA','Moldavsko','Moldova',0),
('ME','MNE','Černá Hora','Montenegro',0),
('MF','MAF','Svatý Martin (Francie)','St. Martin',0),
('MG','MDG','Madagaskar','Madagascar',0),
('MH','MHL','Marshallovy ostrovy','Marshall Islands',0),
('MK','MKD','Severní Makedonie','North Macedonia',0),
('ML','MLI','Mali','Mali',0),
('MM','MMR','Myanmar (Barma)','Myanmar (Burma)',0),
('MN','MNG','Mongolsko','Mongolia',0),
('MO','MAC','Macao','Macao',0),
('MP','MNP','Severní Mariany','Northern Mariana Islands',0),
('MQ','MTQ','Martinik','Martinique',0),
('MR','MRT','Mauritánie','Mauritania',0),
('MS','MSR','Montserrat','Montserrat',0),
('MT','MLT','Malta','Malta',0),
('MU','MUS','Mauricius','Mauritius',0),
('MV','MDV','Maledivy','Maldives',0),
('MW','MWI','Malawi','Malawi',0),
('MX','MEX','Mexiko','Mexico',0),
('MY','MYS','Malajsie','Malaysia',0),
('MZ','MOZ','Mosambik','Mozambique',0),
('NA','NAM','Namibie','Namibia',0),
('NC','NCL','Nová Kaledonie','New Caledonia',0),
('NE','NER','Niger','Niger',0),
('NF','NFK','Norfolk','Norfolk Island',0),
('NG','NGA','Nigérie','Nigeria',0),
('NI','NIC','Nikaragua','Nicaragua',0),
('NL','NLD','Nizozemsko','Netherlands',0),
('NO','NOR','Norsko','Norway',0),
('NP','NPL','Nepál','Nepal',0),
('NR','NRU','Nauru','Nauru',0),
('NU','NIU','Niue','Niue',0),
('NZ','NZL','Nový Zéland','New Zealand',0),
('OM','OMN','Omán','Oman',0),
('PA','PAN','Panama','Panama',0),
('PE','PER','Peru','Peru',0),
('PF','PYF','Francouzská Polynésie','French Polynesia',0),
('PG','PNG','Papua-Nová Guinea','Papua New Guinea',0),
('PH','PHL','Filipíny','Philippines',0),
('PK','PAK','Pákistán','Pakistan',0),
('PL','POL','Polsko','Poland',0),
('PM','SPM','Saint-Pierre a Miquelon','St. Pierre & Miquelon',0),
('PN','PCN','Pitcairnovy ostrovy','Pitcairn Islands',0),
('PR','PRI','Portoriko','Puerto Rico',0),
('PS','PSE','Palestinská území','Palestinian Territories',0),
('PT','PRT','Portugalsko','Portugal',0),
('PW','PLW','Palau','Palau',0),
('PY','PRY','Paraguay','Paraguay',0),
('QA','QAT','Katar','Qatar',0),
('RE','REU','Réunion','Réunion',0),
('RO','ROU','Rumunsko','Romania',0),
('RS','SRB','Srbsko','Serbia',0),
('RU','RUS','Rusko','Russia',0),
('RW','RWA','Rwanda','Rwanda',0),
('SA','SAU','Saúdská Arábie','Saudi Arabia',0),
('SB','SLB','Šalamounovy ostrovy','Solomon Islands',0),
('SC','SYC','Seychely','Seychelles',0),
('SD','SDN','Súdán','Sudan',0),
('SE','SWE','Švédsko','Sweden',0),
('SG','SGP','Singapur','Singapore',0),
('SH','SHN','Svatá Helena','St. Helena',0),
('SI','SVN','Slovinsko','Slovenia',0),
('SJ','SJM','Špicberky a Jan Mayen','Svalbard & Jan Mayen',0),
('SK','SVK','Slovensko','Slovakia',0),
('SL','SLE','Sierra Leone','Sierra Leone',0),
('SM','SMR','San Marino','San Marino',0),
('SN','SEN','Senegal','Senegal',0),
('SO','SOM','Somálsko','Somalia',0),
('SR','SUR','Surinam','Suriname',0),
('SS','SSD','Jižní Súdán','South Sudan',0),
('ST','STP','Svatý Tomáš a Princův ostrov','São Tomé & Príncipe',0),
('SV','SLV','Salvador','El Salvador',0),
('SX','SXM','Svatý Martin (Nizozemsko)','Sint Maarten',0),
('SY','SYR','Sýrie','Syria',0),
('SZ','SWZ','Eswatini','Eswatini',0),
('TC','TCA','Turks a Caicos','Turks & Caicos Islands',0),
('TD','TCD','Čad','Chad',0),
('TF','ATF','Francouzská jižní území','French Southern Territories',0),
('TG','TGO','Togo','Togo',0),
('TH','THA','Thajsko','Thailand',0),
('TJ','TJK','Tádžikistán','Tajikistan',0),
('TK','TKL','Tokelau','Tokelau',0),
('TL','TLS','Východní Timor','Timor-Leste',0),
('TM','TKM','Turkmenistán','Turkmenistan',0),
('TN','TUN','Tunisko','Tunisia',0),
('TO','TON','Tonga','Tonga',0),
('TR','TUR','Turecko','Türkiye',0),
('TT','TTO','Trinidad a Tobago','Trinidad & Tobago',0),
('TV','TUV','Tuvalu','Tuvalu',0),
('TW','TWN','Tchaj-wan','Taiwan',0),
('TZ','TZA','Tanzanie','Tanzania',0),
('UA','UKR','Ukrajina','Ukraine',0),
('UG','UGA','Uganda','Uganda',0),
('UM','UMI','Menší odlehlé ostrovy USA','U.S. Outlying Islands',0),
('US','USA','Spojené státy','United States',0),
('UY','URY','Uruguay','Uruguay',0),
('UZ','UZB','Uzbekistán','Uzbekistan',0),
('VA','VAT','Vatikán','Vatican City',0),
('VC','VCT','Svatý Vincenc a Grenadiny','St. Vincent & Grenadines',0),
('VE','VEN','Venezuela','Venezuela',0),
('VG','VGB','Britské Panenské ostrovy','British Virgin Islands',0),
('VI','VIR','Americké Panenské ostrovy','U.S. Virgin Islands',0),
('VN','VNM','Vietnam','Vietnam',0),
('VU','VUT','Vanuatu','Vanuatu',0),
('WF','WLF','Wallis a Futuna','Wallis & Futuna',0),
('WS','WSM','Samoa','Samoa',0),
('YE','YEM','Jemen','Yemen',0),
('YT','MYT','Mayotte','Mayotte',0),
('ZA','ZAF','Jihoafrická republika','South Africa',0),
('ZM','ZMB','Zambie','Zambia',0),
('ZW','ZWE','Zimbabwe','Zimbabwe',0);

UPDATE tmp_1828_countries s
   SET s.iso3_free = NOT EXISTS (SELECT 1 FROM countries c WHERE UPPER(TRIM(c.iso3)) = s.iso3);

UPDATE countries c
  JOIN tmp_1828_countries s ON UPPER(TRIM(c.iso2)) = s.iso2
   SET c.iso3    = IF(TRIM(c.iso3) = '' AND s.iso3_free = 1, s.iso3, c.iso3),
       c.name_cs = IF(TRIM(c.name_cs) = '', s.name_cs, c.name_cs),
       c.name_en = IF(TRIM(c.name_en) = '', s.name_en, c.name_en);

INSERT INTO countries (iso2, iso3, name_cs, name_en, is_eu)
SELECT s.iso2, s.iso3, s.name_cs, s.name_en, 0
  FROM tmp_1828_countries s
 WHERE NOT EXISTS (
         SELECT 1 FROM countries c
          WHERE UPPER(TRIM(c.iso2)) = s.iso2
             OR UPPER(TRIM(c.iso3)) = s.iso3
       )
 ORDER BY s.iso2;

DROP TEMPORARY TABLE IF EXISTS tmp_1828_countries;
