import { PAYROLL_MANUAL_CHAPTERS } from '@/config/payrollManualChapters'

export type ManualChapterRule = [RegExp, string]

export const MANUAL_CHAPTERS: ManualChapterRule[] = [
  [/^\/imports\/money-s3(?:\/|$)/, '87_Prechod_z_Money_S3'],
  [/^\/accounting\/setup-assistant(?:\/|$)/, '83_Sablony'],
  [/^\/admin\/bank-rule-templates(?:\/|$)/, '83_Sablony'],
  [/^\/templates(?:\/|$)/, '83_Sablony'],
  [/^\/purchase-invoices\/payment-orders(?:\/|$)/, '26_Platebni_prikazy'],
  [/^\/purchase-invoices\/ai-import(?:\/|$)/, '25_AI_extrakce'],
  [/^\/purchase-invoices\/export(?:\/|$)/, '24_Export_prijatych'],
  [/^\/purchase-invoices\/import(?:\/|$)/, '21_Importy'],
  [/^\/purchase-invoices(?:\/|$)/, '23_Prijate_faktury'],
  [/^\/invoices\/ai-import(?:\/|$)/, '21_Importy'],
  [/^\/invoices\/export(?:\/|$)/, '20_Exporty'],
  [/^\/invoices\/import(?:\/|$)/, '21_Importy'],
  [/^\/invoices\/new(?:\/|$)/, '15_Faktura_editor'],
  [/^\/invoices\/\d+(?:\/|$)/, '16_Faktura_PDF'],
  [/^\/invoices(?:\/|$)/, '14_Faktury'],
  [/^\/recurring(?:\/|$)/, '17_Pravidelne_fakturace'],
  [/^\/clients(?:\/|$)/, '18_Klienti'],
  [/^\/projects(?:\/|$)/, '19_Zakazky'],
  [/^\/bank(?:\/|$)/, '28_Banka'],
  [/^\/gopay(?:\/|$)/, '30_GoPay'],
  [/^\/accounting\/cash(?:\/|$)/, '31_Pokladna'],
  [/^\/documents(?:\/|$)|^\/document-requests(?:\/|$)/, '32_Dokumenty'],
  [/^\/logbook(?:\/|$)/, '34_Kniha_jizd'],
  [/^\/stock(?:\/|$)/, '35_Sklad'],
  [/^\/eshop\/shoptet(?:\/|$)/, '37_Shoptet'],
  [/^\/eshop(?:\/|$)/, '36_Eshop'],
  [/^\/reports\/dph-book(?:\/|$)/, '40_Kniha_DPH'],
  [/^\/reports\/shv(?:\/|$)/, '42_Souhrnne_hlaseni'],
  [/^\/reports\/oss(?:\/|$)/, '43_OSS'],
  [/^\/reports\/income-tax(?:\/|$)/, '41_Dan_z_prijmu'],
  // Oznámení podle § 38da a § 38e je popsané v kapitole o dani z příjmů,
  // ne u mezd: mzdových příjmů se obě podání netýkají.
  [/^\/reports\/foreign-income(?:\/|$)/, '41_Dan_z_prijmu'],
  [/^\/reports\/submissions(?:\/|$)/, '93_Archiv_podani_a_rekonciliace'],
  [/^\/reports\/monthly-export(?:\/|$)/, '45_Hromadny_export'],
  [/^\/reports\/(?:dph|kh|s74b|vat-corrections|vat-coefficient|s46)(?:\/|$)/, '39_Vykazy_DPH'],
  [/^\/reports\/(?:cnb-rate-audit|invoice-series-completeness)(?:\/|$)/, '82_Ucetni_kontroly_a_inventarizace'],
  [/^\/tax(?:\/|$)/, '44_Danovy_optimalizator'],
  [/^\/portfolio(?:\/|$)/, '47_Prehled_firem'],
  [/^\/automation(?:\/|$)/, '49_Automat'],
  [/^\/accounting\/manual-posting-queue(?:\/|$)/, '50_Rucni_fronta_doctovani'],
  [/^\/accounting\/general-ledger(?:\/|$)/, '51_Hlavni_kniha'],
  [/^\/accounting\/trial-balance(?:\/|$)/, '52_Obratova_predvaha'],
  [/^\/accounting\/balance-sheet(?:\/|$)/, '53_Rozvaha'],
  [/^\/accounting\/statement-mapping(?:\/|$)/, '53_Rozvaha'],
  [/^\/accounting\/income-statement-by-function(?:\/|$)/, '55_Vysledovka_ucelova'],
  [/^\/accounting\/income-statement(?:\/|$)/, '54_Vysledovka_druhova'],
  [/^\/accounting\/saldo(?:\/|$)/, '56_Saldokonto'],
  [/^\/accounting\/document-completeness(?:\/|$)/, '57_Uplnost_dokladu'],
  [/^\/accounting\/monthly-check(?:\/|$)/, '58_Mesicni_kontrola'],
  [/^\/accounting\/monthly-report(?:\/|$)/, '59_Mesicni_report'],
  ...PAYROLL_MANUAL_CHAPTERS,
  [/^\/accounting\/payroll(?:\/|$)/, '60_Mzdy'],
  [/^\/accounting\/assets(?:\/|$)|^\/accounting\/small-assets(?:\/|$)/, '81_Majetek'],
  [/^\/accounting\/accounts(?:\/|$)/, '84_Ucetni_osnova'],
  [/^\/accounting\/offsets(?:\/|$)/, '85_Zapocty'],
  [/^\/admin\/accounting-activation(?:\/|$)/, '86_Aktivace_ucetnictvi'],
  [/^\/accounting\/balance-inventory(?:\/|$)/, '88_Inventarizace_rozvahovych_uctu'],
  [/^\/accounting\/section18-statements(?:\/|$)/, '89_Vykazy_podle_paragrafu_18'],
  [/^\/reports\/related-parties(?:\/|$)/, '90_Propojene_osoby'],
  [/^\/accounting\/periods(?:\/|$)/, '91_Uzaverka'],
  [/^\/accounting\/journal(?:\/|$)/, '48_Ucetni_denik'],
  [/^\/accounting(?:\/|$)|^\/utilities(?:\/|$)/, '92_Ucetni_nastroje'],
  [/^\/tax-evidence(?:\/|$)/, '94_Danova_evidence'],
  [/^\/admin\/suppliers(?:\/|$)/, '95_Multi_supplier'],
  [/^\/payment-cards(?:\/|$)/, '97_Platebni_karty'],
  [/^\/admin\/databox(?:\/|$)/, '98_Datova_schranka'],
  [/^\/admin\/isds-gateway(?:\/|$)/, '99_Odesilaci_brana_ISDS'],
  [/^\/isds-gateway\/callback(?:\/|$)/, '99_Odesilaci_brana_ISDS'],
  [/^\/admin\/electronic-signatures(?:\/|$)/, '100_Elektronicke_podpisy'],
  [/^\/admin\/tax-constants(?:\/|$)/, '101_Danove_konstanty'],
  [/^\/admin\/(?:users|roles|activity-log|cron-jobs)(?:\/|$)/, '102_Bezpecnost'],
  [/^\/admin\/update(?:\/|$)/, '103_Aktualizace'],
  [/^\/admin\/(?:diagnostics|support)(?:\/|$)/, '999_Reseni_problemu'],
  [/^\/profile\/mcp-server(?:\/|$)/, '106_MCP_server'],
  [/^\/profile\/api-tokens(?:\/|$)/, '104_API'],
  [/^\/activation(?:\/|$)|^\/hosting(?:\/|$)/, '105_Licence_a_aktivace'],
  [/^\/admin(?:\/|$)/, '96_Nastaveni'],
  [/^\/profile(?:\/|$)/, '102_Bezpecnost'],
  [/^\/portal(?:\/|$)/, '09_Klientsky_portal'],
  [/^\/crm(?:\/|$)/, '11_Zisk'],
  [/^\/stats(?:\/|$)/, '12_Trzby'],
  [/^\/purchase-stats(?:\/|$)/, '13_Naklady'],
  [/^\/$/, '10_Prehled'],
]

export function manualChapter(path: string): string | undefined {
  return MANUAL_CHAPTERS.find(([pattern]) => pattern.test(path))?.[1]
}
